name = "glenca"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "8ccba74c558243f791d069bf921d453b"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "db633625-fb5b-4de1-92fe-2244dd58cf0a"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/hounna19/newrepo/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/hounna19/newrepo/refs/heads/master/web/sub.html"
